on:
  push:
  pull_request:

name: run_nextflow

jobs:
  run_nextflow:

    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - uses: stracquadaniolab/gh-action-setup-nextflow

      - name: Run
        run: nextflow run main.nf -resume -entry prep

